In [2]:
import imagehash
from PIL import Image

In [24]:
import numpy as np
im = Image.fromarray(np.random.random((55,55)))
mat = np.asarray(im)
print(mat)
p = imagehash.phash(image=im)
print(p)

[[0.6408839  0.81618565 0.14744984 ... 0.9429941  0.5110945  0.7155368 ]
 [0.197784   0.09441432 0.1095331  ... 0.20932129 0.01880535 0.07657995]
 [0.1308591  0.95171976 0.807194   ... 0.50998324 0.01561761 0.70832944]
 ...
 [0.5069705  0.6392497  0.20520447 ... 0.48758897 0.4372476  0.596303  ]
 [0.9873052  0.75777835 0.46222815 ... 0.70356727 0.42464024 0.28079882]
 [0.43060678 0.9048166  0.28205168 ... 0.0125348  0.52196616 0.0733337 ]]
0000000000000000


In [25]:
max = mat.max()
min = mat.min()
scale=255/(max-min)

In [26]:
mat = (mat - min )*scale


array([[163.40074  , 208.11784  ,  37.532383 , ..., 240.46497  ,
        130.29321  , 182.44366  ],
       [ 50.371952 ,  24.00374  ,  27.860336 , ...,  53.314957 ,
          4.716914 ,  19.454433 ],
       [ 33.300316 , 242.69075  , 205.82419  , ..., 130.00975  ,
          3.9037647, 180.60518  ],
       ...,
       [129.24124  , 162.98387  ,  52.264812 , ..., 124.29728  ,
        111.45587  , 152.02875  ],
       [251.76813  , 193.21892  , 117.82807  , ..., 179.39041  ,
        108.23991  ,  71.547905 ],
       [109.761894 , 230.7264   ,  71.86749  , ...,   3.1173828,
        133.06642  ,  18.626358 ]], dtype=float32)

In [28]:

mat.max()

255.0

In [2]:
hash = imagehash.phash(Image.open('imagestocompare/original.png'))
print(hash)

aa5555aaa955aaaa


In [3]:
otherhash = imagehash.phash(Image.open('imagestocompare/hashimg3.png'))
print(otherhash)

print(hash == otherhash)
print(hash-otherhash)

aa5555aaa955aaaa
True
0
